public class PaymentInputDetailTemp {
	public string referenceNo {get; set;}
    public string PaymentDate {get; set;}
    public string startDate {get; set;}
    public string Payment {get; set;}
    public string Pocketpayment {get; set;}
    
    public string personCode {get; set;}
    public string Bank_account_Nominee {get; set;}
    public string Financial_Name {get; set;}
    public string Financial_branch {get; set;}
    public string cancelType {get; set;}
    public string EDI {get; set;}
    public string dami {get; set;}
    
    public string errorFlg {get; set;}
    //挿入フラグ
	public string insertFlg {get; set;}
    //更新フラグ
	public string updateFlg {get; set;}    
}